#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3

## Allocate 10 ports per node
##   .7 - http

NUMBER=${NAME##dev}
BASE=$((10000 + 100 * $NUMBER))
WEBPORT=$(($BASE + 8))
HANDOFFPORT=$(($BASE + 9))
NODENAME="udon$NUMBER@127.0.0.1"
SNAME="udon$NUMBER"
REDISPORT=$((BASE + 10))

echo "Generating $NAME - node='$NODENAME' sname='$SNAME' http=$WEBPORT handoff=$HANDOFFPORT redis=$REDISPORT"
sed -e "s/@NODE@/$NODENAME/" \
    -e "s/@WEBPORT@/$WEBPORT/" \
    -e "s/@HANDOFFPORT@/$HANDOFFPORT/" \
    -e "s/@REDISPORT@/$REDISPORT/" \
    -e "s/@SNAME@/$SNAME/" \
     < $TEMPLATE > $VARFILE
